# Dados de acesso ao MySQL (tambem podem ser alterados na tela de conexao)
db.url=jdbc:mysql://localhost:3306/hortifruti?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Recife
db.user=root
db.password=
